### ISSUE TITLE
eyes coloration

### ISSUE THREAD

**Issue by vespersland** [felixrosberg/FaceDancer#12]
Thanks for your great work!I've noticed that eyes coloration doesn't always match with the source especially with light eyes.
There is a way to fix this?

thanks in advance

**Comment by felixrosberg** [comment]
Hi @vespersland ,

Thank you! Yes eyes are notoriously tricky, especielly with target-oriented face swapping. Probably due to how small the eye region is compared to the whole image. There is sadly no quick fix for this. You would have to retrain the FaceDancer with some additional loss such a secondary discriminator that focus on eyes only. Even this would not guarantee correct eye color, only improve visual quality. Another possible solution would have a iris recognition model as a eye identity loss. I may try this out in the future, no guarantees. :)
