### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by netrunner-exe** [felixrosberg/FaceDancer#2]
Hi @felixrosberg! While running the code, I encountered the following error:
```
Traceback (most recent call last):
  File "video_swap/multi_face_single_source.py", line 1, in <module>
    from utils.utils import norm_crop, estimate_norm, inverse_estimate_norm, transform_landmark_points, get_lm
ModuleNotFoundError: No module named 'utils'
```

Fast solution is add sys.path.append to the beginning of `multi_face_single_source.py`
```
import sys
sys.path.append('.')
```
Or
```
import sys
sys.path.insert (0, '.')
```
and change in `--retina_path and` `--arcface_path` and `--facedancer_path` `../` to `./`
I tested your project on huggingface, the result is amazing! Would love to try it on video, do you plan to share the `FaceDancer-HQ.h5` pretrained model?

**Comment by felixrosberg** [comment]
Hi @netrunner-exe ,

Odd, this could be because I have only really tested the code base in PyCharm and that the imports is handled differently there. However this kind of import do seem to work fine on the HuggingFace server. I will look into it.

Thank you!
Yes, the all models in the paper and any extra models such as the HQ version will be shared by the end of the month. I am just finishing up some licensing.
