### ISSUE TITLE
about resolution faces

### ISSUE THREAD

**Issue by 1406428260** [felixrosberg/FaceDancer#36]
1.I test model about config_a.h5 b c cHD..., You said  HD model is high resolution faces. But network input and outpu also is 256*256，what's difference about HD and other model?
2.could you explain the difference about *.h5 and *_tuned.h5？
3.
![image](https://user-images.githubusercontent.com/41857725/234804784-b2121e0b-0361-4afd-be09-70926659541e.png)
why source image with high resolution no good , whatever source image input  must aligned to arcface and resize 256*256 to input network

thank you very much!

**Comment by 1406428260** [comment]
by the way ，another question:
i just pick 2 faces to test training result（source always one persion;target always one persion）, the result like this:
![Snipaste_2023-04-28_15-17-36](https://user-images.githubusercontent.com/41857725/235080757-fbb4709d-ac41-4bf9-95be-dd5ea0c00600.jpg)

1.when align face it is inevitable that some large angle face can not be aligned like this
![nQ1pzo6TNWBDkLyoqZ9XC2j883wwx3](https://user-images.githubusercontent.com/41857725/235078755-a49ff43a-acb0-4bc3-a626-15af4f849d1c.jpg)
![f23c911ff529507f77c49c5f3d666719](https://user-images.githubusercontent.com/41857725/235079377-748d2d77-41c3-4e0d-8653-dbef8914473a.jpg)

so how to process these faces? 
2.if train dataset remove these faces , how to deal with when infer really target img has same pose?

**Comment by felixrosberg** [comment]
First the models and model names are detailed here: https://huggingface.co/felixrosberg/FaceDancer

The HD means the fidelity of the image used is high and has nothing to do with the 256 by 256 input. For example you can have 256 by 256 images that are pixely or blurry and you can have 256 by 256 images without these distortions. .h5 models were trained for 300k iterations and _tuned.h5 were trained for 500k iterations.

By source image, I mean the unaligned image. Meaning that too high resolution may cause the face detector to not find the face. This can be adjusted by down scaling large images. I have this function programmed for the target image but not the source image currently.

I am not sure I understand your second question. The example image of large angle faces can indeed be aligned. If the detector fails to find the keypoints (due to too large image?) the alignment will fail. I have had no issues aligning difficult poses. There are examples in the paper.

"2.if train dataset remove these faces , how to deal with when infer really target img has same pose?" I think you have to rephrase this question, I do not understand. I can add that the preprocessing step does not remove any faces due to alignment, only due to user specified minimum allow resolution of the face.

**Comment by 1406428260** [comment]
Thanks for your reply!
about "The example image of large angle faces can indeed be aligned" which I mean is some images with those large angle ，aligned like this 
![image](https://user-images.githubusercontent.com/41857725/236121107-3609a446-a24b-42a3-a85c-fb4621eeca4b.png)
it's not like this 
![image](https://user-images.githubusercontent.com/41857725/236121182-ffccbac8-5d30-4dcb-984c-92f9dac7a6b5.png)
Is these tarin dataset fine ?

**Comment by felixrosberg** [comment]
Hi,

So aligned does not mean turning the face. It is an affine transformation that rotates, scales and crop the image to match the keypoints to its best ability. Your second image here is basically the desired position of eyes, nose and mouth. When we have images with large angle, it will calculate the affine transformation that yield the least error/distance to something similar as below.

So to clarify, alignment only rotates/scales/crops 2d images. Of course, large angles are notorious difficult to deal with in face swapping for several reasons: mostly unbalanced data (more forward facing images).

**Comment by 1406428260** [comment]
thanks a lot!
